CREATE TABLE `recessi_luce` (
	`ID_RECESSO_LUCE` INT(255) NOT NULL AUTO_INCREMENT,
	`POD` VARCHAR(50) NULL DEFAULT NULL,
	`CD_TP_UTENZA` VARCHAR(50) NULL DEFAULT NULL,
	`INSOLUTO` VARCHAR(50) NULL DEFAULT NULL,
	`RAGIONE_SOCIALE` VARCHAR(100) NULL DEFAULT NULL,
	`INDIRIZZO_SEDE_LEGALE` VARCHAR(100) NULL DEFAULT NULL,
	`LOCALITA_SEDE_LEGALE` VARCHAR(100) NULL DEFAULT NULL,
	`INDIRIZZO_FORN` VARCHAR(100) NULL DEFAULT NULL,
	`LOCALITA_FORN` VARCHAR(100) NULL DEFAULT NULL,
	`TELEFONO` VARCHAR(20) NULL DEFAULT NULL,
	`CELLULARE` VARCHAR(20) NULL DEFAULT NULL,
	`KWH_ANNUI` VARCHAR(50) NULL DEFAULT NULL,
	`DATA_ATTIVAZIONE` DATE NULL DEFAULT NULL,
	`DATA_VALIDITA_RECESSO` DATE NULL DEFAULT NULL,
	`NOTA_RECESSO` VARCHAR(200) NULL DEFAULT NULL,
	`AGENZIA` VARCHAR(40) NULL DEFAULT NULL,
	`GRUPPO` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`ID_RECESSO_LUCE`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `recessi_gas` (
	`ID_RECESSO_GAS` INT(255) NOT NULL AUTO_INCREMENT,
	`PDR` VARCHAR(50) NULL DEFAULT NULL,
	`DENOMINAZIONE` VARCHAR(100) NULL DEFAULT NULL,
	`VIA` VARCHAR(100) NULL DEFAULT NULL,
	`LOCALITA` VARCHAR(100) NULL DEFAULT NULL,
	`PROVINCIA` VARCHAR(100) NULL DEFAULT NULL,
	`CONSUMO_CONTRATTUALE` VARCHAR(50) NULL DEFAULT NULL,
	`RIF_TELEFONICI` VARCHAR(20) NULL DEFAULT NULL,
	`AGENTE` VARCHAR(100) NULL DEFAULT NULL,
	`CAPO_AREA` VARCHAR(20) NULL DEFAULT NULL,
	`DATA_INIZIO_FORNITURA` DATE NULL DEFAULT NULL,
	`DATA_OUT` DATE NULL DEFAULT NULL,
	`OFFERTA` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`ID_RECESSO_GAS`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `dettaglio_recesso_gas` (
	`ID_DETTAGLIO_GAS` INT(255) NOT NULL AUTO_INCREMENT,
	`ID_RECESSO_GAS` INT(255) NOT NULL,
	`VENDITORE_ASSEGNATO` INT(255) NULL DEFAULT NULL,
	`DATA_INSERIMENTO` DATETIME NOT NULL,
	`ULTIMA_MODIFICA` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`REFERENTE_RECESSO` VARCHAR(30) NULL DEFAULT NULL,
	`STATO` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`ID_DETTAGLIO_GAS`),
	INDEX `ID_RECESSO_GAS` (`ID_RECESSO_GAS`),
	INDEX `ID_ASSEGNATARIO` (`VENDITORE_ASSEGNATO`),
	CONSTRAINT `FK_dettaglio_recesso_gas_recessi_gas` FOREIGN KEY (`ID_RECESSO_GAS`) REFERENCES `recessi_gas` (`ID_RECESSO_GAS`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_dettaglio_recesso_gas_utenti` FOREIGN KEY (`VENDITORE_ASSEGNATO`) REFERENCES `utenti` (`ID_UTENTE`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `dettaglio_recesso_luce` (
	`ID_DETTAGLIO_LUCE` INT(255) NOT NULL AUTO_INCREMENT,
	`ID_RECESSO_LUCE` INT(255) NOT NULL,
	`VENDITORE_ASSEGNATO` INT(255) NULL DEFAULT NULL,
	`DATA_INSERIMENTO` DATETIME NOT NULL,
	`ULTIMA_MODIFICA` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`REFERENTE_RECESSO` VARCHAR(30) NULL DEFAULT NULL,
	`STATO` VARCHAR(20) NOT NULL DEFAULT '',
	PRIMARY KEY (`ID_DETTAGLIO_LUCE`),
	INDEX `ID_RECESSO_LUCE` (`ID_RECESSO_LUCE`),
	INDEX `ID_ASSEGNATARIO` (`VENDITORE_ASSEGNATO`),
	CONSTRAINT `FK_ASSEGNATARIO` FOREIGN KEY (`VENDITORE_ASSEGNATO`) REFERENCES `utenti` (`ID_UTENTE`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_dettaglio_recesso_luce_recessi_luce` FOREIGN KEY (`ID_RECESSO_LUCE`) REFERENCES `recessi_luce` (`ID_RECESSO_LUCE`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
